// Generated by CoffeeScript 1.8.0
(function() {
  var ItemBaseComponent, ItemImageComponent, ItemTextComponent,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  $(function() {
    var builder, img, text;
    img = new ItemImageComponent;
    text = new ItemTextComponent;
    return builder = new Vue({
      el: '#wrapper',
      components: {
        red: {
          template: '#red-template'
        },
        blue: {
          template: '#blue-template'
        }
      },
      data: {
        containers: [
          {
            component: 'red',
            name: 'red',
            items: [
              {
                component: 'item-image-component',
                src: 'https://fbcdn-sphotos-f-a.akamaihd.net/hphotos-ak-xap1/v/t1.0-9/1461847_620993098012076_730628183140157389_n.jpg?oh=29fc0fc7d7cf538f8bd0416004b4b13f&oe=54FAE28F&__gda__=1426473842_887ce6c8b023ab0f04828d3176338ba5'
              }, {
                component: 'item-text-component'
              }
            ]
          }, {
            component: 'blue',
            name: 'blue'
          }
        ]
      }
    });
  });

  ItemBaseComponent = (function() {
    var dashnize;

    dashnize = function(str) {
      return str.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
    };

    function ItemBaseComponent(config) {
      this.config = config != null ? config : {};
      this.config = $.extend(this.constructor.defaultConfig, this.config);
      this.componentName = dashnize(this.constructor.name);
      Vue.component(this.componentName, {
        template: "#" + this.componentName,
        data: (function(_this) {
          return function() {
            return _this.config;
          };
        })(this)
      });
      if (typeof this.init === "function") {
        this.init();
      }
    }

    return ItemBaseComponent;

  })();

  ItemImageComponent = (function(_super) {
    __extends(ItemImageComponent, _super);

    function ItemImageComponent() {
      return ItemImageComponent.__super__.constructor.apply(this, arguments);
    }

    ItemImageComponent.defaultConfig = {
      src: 'https://scontent-b.xx.fbcdn.net/hphotos-xap1/v/t1.0-9/10702230_864194103591492_1872941301669900458_n.jpg?oh=cab12c388dfbace6baf9dcf11ba28193&oe=5543E106'
    };

    ItemImageComponent.prototype.init = function() {};

    return ItemImageComponent;

  })(ItemBaseComponent);

  ItemTextComponent = (function(_super) {
    __extends(ItemTextComponent, _super);

    function ItemTextComponent() {
      return ItemTextComponent.__super__.constructor.apply(this, arguments);
    }

    ItemTextComponent.defaultConfig = {
      text: 'aaaaaa',
      size: '24px',
      color: '#ff0000',
      align: 'center'
    };

    ItemTextComponent.prototype.init = function() {};

    return ItemTextComponent;

  })(ItemBaseComponent);

}).call(this);
