// Generated by CoffeeScript 1.8.0
(function() {
  var Component, ItemBaseComponent, ItemImageComponent, ItemStringComponent, ItemTextComponent, LayoutBaseComponent, LayoutCol12Component, LayoutCol6Component,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  $(function() {
    var builder;
    Vue.component('layout-col-12-component', {
      template: '#layout-col-12-component'
    });
    Vue.component('layout-col-6-component', {
      template: '#layout-col-6-component'
    });
    Vue.component('container-vertival-component', {
      template: '#container-vertival-component'
    });
    return builder = new Vue({
      el: '#wrapper',
      data: {
        layouts: [
          {
            layout: 'layout-col-12-component',
            innerStyle: {
              'background-color': '#ff0000'
            },
            container: {
              items: [
                {
                  name: '111'
                }, {
                  name: '222'
                }, {
                  name: '333'
                }
              ]
            }
          }, {
            layout: 'layout-col-6-component',
            innerStyle: {
              'background-color': '#ff0000'
            },
            firstContainer: {
              items: [
                {
                  name: '111'
                }, {
                  name: '222'
                }, {
                  name: '333'
                }
              ]
            },
            secondContainer: {
              items: [
                {
                  name: '111'
                }, {
                  name: '222'
                }, {
                  name: '333'
                }
              ]
            }
          }
        ]
      }
    });
  });

  Component = (function() {
    var dashnize;

    dashnize = function(str) {
      str = str.replace(/[A-Z]/g, function(char, index) {
        return (index !== 0 ? "-" : "") + char.toLowerCase();
      });
      return str = str.replace(/[0-9]+/g, function(char, index) {
        return (index !== 0 ? "-" : "") + char;
      });
    };

    function Component(config) {
      this.config = config != null ? config : {};
      this.config = $.extend(this.constructor.defaultConfig, this.config);
      this.componentName = dashnize(this.constructor.name);
    }

    return Component;

  })();

  LayoutBaseComponent = (function(_super) {
    __extends(LayoutBaseComponent, _super);

    function LayoutBaseComponent(config) {
      this.config = config != null ? config : {};
      LayoutBaseComponent.__super__.constructor.call(this, this.config);
      Vue.component(this.componentName, {
        template: "#" + this.componentName,
        methods: {
          addChild: function() {
            return this.$parent.items.splice(this.$index + 1, 0, {
              component: 'item-image-component'
            });
          }
        },
        data: (function(_this) {
          return function() {
            return _this.config;
          };
        })(this)
      });
      if (typeof this.init === "function") {
        this.init();
      }
    }

    return LayoutBaseComponent;

  })(Component);

  LayoutCol12Component = (function(_super) {
    __extends(LayoutCol12Component, _super);

    function LayoutCol12Component() {
      return LayoutCol12Component.__super__.constructor.apply(this, arguments);
    }

    LayoutCol12Component.defaultConfig = {
      model: {
        text: 'aaaaaa',
        size: '24px',
        color: '#ff0000',
        align: 'center'
      }
    };

    LayoutCol12Component.prototype.init = function() {};

    return LayoutCol12Component;

  })(LayoutBaseComponent);

  LayoutCol6Component = (function(_super) {
    __extends(LayoutCol6Component, _super);

    function LayoutCol6Component() {
      return LayoutCol6Component.__super__.constructor.apply(this, arguments);
    }

    LayoutCol6Component.defaultConfig = {
      model: {
        text: 'aaaaaa',
        size: '24px',
        color: '#ff0000',
        align: 'center'
      }
    };

    LayoutCol6Component.prototype.init = function() {};

    return LayoutCol6Component;

  })(LayoutBaseComponent);

  ItemBaseComponent = (function(_super) {
    __extends(ItemBaseComponent, _super);

    function ItemBaseComponent(config) {
      this.config = config != null ? config : {};
      ItemBaseComponent.__super__.constructor.call(this, this.config);
      this.component = Vue.component(this.componentName, {
        template: "#" + this.componentName,
        directives: {
          editable: {
            bind: function() {
              new MediumEditor(this.el, this.vm.editable);
              $(this.el).html(this.vm.model.text);
              return $(this.el).on('input', (function(_this) {
                return function(e) {
                  return _this.vm.model.text = $(e.target).html();
                };
              })(this));
            }
          }
        },
        methods: {
          addChild: function() {
            return this.$parent.items.splice(this.$index + 1, 0, {
              component: 'item-image-component'
            });
          }
        },
        data: (function(_this) {
          return function() {
            return _this.config;
          };
        })(this)
      });
      if (typeof this.init === "function") {
        this.init();
      }
    }

    return ItemBaseComponent;

  })(Component);

  ItemImageComponent = (function(_super) {
    __extends(ItemImageComponent, _super);

    function ItemImageComponent() {
      return ItemImageComponent.__super__.constructor.apply(this, arguments);
    }

    ItemImageComponent.defaultConfig = {
      model: {
        src: 'https://scontent-b.xx.fbcdn.net/hphotos-xap1/v/t1.0-9/10702230_864194103591492_1872941301669900458_n.jpg?oh=cab12c388dfbace6baf9dcf11ba28193&oe=5543E106'
      },
      medium: {
        element: null
      }
    };

    ItemImageComponent.prototype.init = function() {};

    return ItemImageComponent;

  })(ItemBaseComponent);

  ItemStringComponent = (function(_super) {
    __extends(ItemStringComponent, _super);

    function ItemStringComponent() {
      return ItemStringComponent.__super__.constructor.apply(this, arguments);
    }

    ItemStringComponent.defaultConfig = {
      model: {
        text: 'aaaaaa',
        size: '24px',
        color: '#ff0000',
        align: 'center'
      },
      editable: {
        disableReturn: true,
        disableToolbar: true
      }
    };

    ItemStringComponent.prototype.init = function() {};

    return ItemStringComponent;

  })(ItemBaseComponent);

  ItemTextComponent = (function(_super) {
    __extends(ItemTextComponent, _super);

    function ItemTextComponent() {
      return ItemTextComponent.__super__.constructor.apply(this, arguments);
    }

    ItemTextComponent.defaultConfig = {
      model: {
        text: 'aaa',
        size: '24px',
        color: '#ff0000',
        align: 'center'
      },
      editable: {
        disableReturn: false,
        disableToolbar: false
      }
    };

    ItemTextComponent.prototype.init = function() {};

    return ItemTextComponent;

  })(ItemBaseComponent);

}).call(this);
