// Generated by CoffeeScript 1.8.0
(function() {
  var BaseItem,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BaseItem = (function(_super) {
    __extends(BaseItem, _super);

    function BaseItem(config) {
      this.config = config != null ? config : {};
      BaseItem.__super__.constructor.call(this, this.config);
      this.component = Vue.component(this.componentName, {
        template: "#" + this.componentName,
        directives: {
          editable: {
            bind: function() {
              new MediumEditor(this.el, this.vm.editable);
              $(this.el).html(this.vm.model.text);
              return $(this.el).on('input', (function(_this) {
                return function(e) {
                  return _this.vm.model.text = $(e.target).html();
                };
              })(this));
            }
          }
        },
        methods: {
          addChild: function() {
            return this.$parent.items.splice(this.$index + 1, 0, {
              component: 'item-image-component'
            });
          }
        },
        data: (function(_this) {
          return function() {
            return _this.config;
          };
        })(this)
      });
      if (typeof this.init === "function") {
        this.init();
      }
    }

    return BaseItem;

  })(Component);

}).call(this);
