// Generated by CoffeeScript 1.8.0
(function() {
  var ContainerBaseComponent,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ContainerBaseComponent = (function(_super) {
    __extends(ContainerBaseComponent, _super);

    function ContainerBaseComponent() {
      return ContainerBaseComponent.__super__.constructor.apply(this, arguments);
    }

    ContainerBaseComponent.prototype.init = function() {};

    return ContainerBaseComponent;

  })(LayoutBaseComponent);

}).call(this);
