// Generated by CoffeeScript 1.8.0
(function() {
  var ItemStringComponent,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ItemStringComponent = (function(_super) {
    __extends(ItemStringComponent, _super);

    function ItemStringComponent() {
      return ItemStringComponent.__super__.constructor.apply(this, arguments);
    }

    ItemStringComponent.defaultConfig = {
      model: {
        text: 'aaaaaa',
        size: '24px',
        color: '#ff0000',
        align: 'center'
      },
      medium: {
        mode: Medium.inlineMode
      }
    };

    ItemStringComponent.prototype.init = function() {};

    return ItemStringComponent;

  })(ItemBaseComponent);

}).call(this);
