// Generated by CoffeeScript 1.8.0
(function() {
  var LayoutCol12Component,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  LayoutCol12Component = (function(_super) {
    __extends(LayoutCol12Component, _super);

    function LayoutCol12Component() {
      return LayoutCol12Component.__super__.constructor.apply(this, arguments);
    }

    LayoutCol12Component.defaultConfig = {
      model: {
        text: 'aaaaaa',
        size: '24px',
        color: '#ff0000',
        align: 'center'
      },
      editable: {
        disableReturn: true,
        disableToolbar: true
      }
    };

    LayoutCol12Component.prototype.init = function() {};

    return LayoutCol12Component;

  })(LayoutBaseComponent);

}).call(this);
