// Generated by CoffeeScript 1.8.0
(function() {
  var TwoColLayout,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  TwoColLayout = (function(_super) {
    __extends(TwoColLayout, _super);

    function TwoColLayout() {
      return TwoColLayout.__super__.constructor.apply(this, arguments);
    }

    TwoColLayout.defaultConfig = {
      innerStyle: {
        'background-color': '#ff0000'
      },
      container: [
        {
          items: []
        }, {
          items: []
        }
      ]
    };

    TwoColLayout.prototype.init = function() {};

    return TwoColLayout;

  })(LayoutBaseComponent);

}).call(this);
