// Generated by CoffeeScript 1.8.0
(function() {
  var OneColLayout,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  OneColLayout = (function(_super) {
    __extends(OneColLayout, _super);

    function OneColLayout() {
      return OneColLayout.__super__.constructor.apply(this, arguments);
    }

    OneColLayout.defaultConfig = {
      innerStyle: {
        'background-color': '#ff0000'
      },
      container: {
        items: []
      }
    };

    OneColLayout.prototype.init = function() {};

    return OneColLayout;

  })(LayoutBaseComponent);

}).call(this);
