// Generated by CoffeeScript 1.8.0
(function() {
  var SmallGridLayout,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  SmallGridLayout = (function(_super) {
    __extends(SmallGridLayout, _super);

    function SmallGridLayout() {
      return SmallGridLayout.__super__.constructor.apply(this, arguments);
    }

    SmallGridLayout.defaultConfig = {
      innerStyle: {
        'background-color': '#ff0000'
      },
      container: {
        items: []
      }
    };

    SmallGridLayout.prototype.init = function() {};

    return SmallGridLayout;

  })(LayoutBaseComponent);

}).call(this);
