// Generated by CoffeeScript 1.8.0
(function() {
  var SmallGridContainer,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  SmallGridContainer = (function(_super) {
    __extends(SmallGridContainer, _super);

    function SmallGridContainer() {
      return SmallGridContainer.__super__.constructor.apply(this, arguments);
    }

    SmallGridContainer.prototype.init = function() {};

    return SmallGridContainer;

  })(ContainerBaseComponent);

}).call(this);
